In [1]:
# import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [4]:
# import dataset\
spam_df = pd.read_csv("spam.csv")


In [7]:
# inspect data
spam_df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [8]:
# turn spam/ham into numerical data, creating a new column called 'spam'

spam_df['spam'] = spam_df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [13]:
# create train.test split
x_train,x_test, y_train,y_test = train_test_split(spam_df.Message, spam_df.spam, test_size = 0.25)

In [16]:
#find word count and store data in a matrix
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [25]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
# train model
model = MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [36]:
# pre test ham
sms_ham = ["We got Baseball tickets for you click here to know more"]
sms_ham_count = cv.transform(sms_ham)
model.predict(sms_ham_count)

array([0], dtype=int64)

In [37]:
# pre test spam
sms_spam = ["Reward has been sent to you. Click here to win"]
sms_spam_count = cv.transform(sms_spam)
model.predict(sms_spam_count)

array([1], dtype=int64)

In [38]:
# test model

x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9806173725771715