In [12]:
# Write a pandas progrma to compute the minumun, 25th percentile and median and 75th and maximum
import pandas as pd
import numpy as np
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10,4,20))
print("Original Series")
print(num_series)
result = np.percentile(num_series,q=[0,25,50,75,100])
print("\n Minimum, 25th Percentile, median, 75th and maximum of a given series")
print(result)

Original Series
0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

 Minimum, 25th Percentile, median, 75th and maximum of a given series
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


In [11]:
num_series.describe()

count    20.000000
mean      9.985279
std       3.145584
min       3.000938
25%       8.094639
50%      10.233537
75%      12.215377
max      14.612143
dtype: float64

In [18]:
# Write a pandas progrma to calculate the frequency counts of each unique value of a given series
import numpy as np
import pandas as pd

num_series = pd.Series(np.take(list('0123456789'),np.random.randint(10,size=100)))
print(num_series)
print("Frequency Counts of each unique value of the said series")
result = num_series.value_counts()
print(result)

0     0
1     0
2     9
3     8
4     4
     ..
95    1
96    2
97    4
98    4
99    8
Length: 100, dtype: object
Frequency Counts of each unique value of the said series
4    19
0    12
8    12
1    12
7    11
6    10
3     9
5     6
2     6
9     3
Name: count, dtype: int64


In [23]:
# Write a pandas program to find the position of number that are multiple of 5 of a given series.
import pandas as pd
import numpy as np

num_series = pd.Series(np.random.randint(1,10,10))
print("Original Series")
print(num_series)
result = np.where(num_series % 5 ==0)
print(result)

Original Series
0    3
1    5
2    7
3    1
4    8
5    5
6    6
7    3
8    9
9    9
dtype: int32
(array([1, 5], dtype=int64),)


In [26]:
# Write a pandas program to extract items at given position of a given series
import pandas as pd

ser = pd.Series([10,20,30,40,50,60,70,80,90])
print("Original Series")
print(ser)
x = [4,5,6]
result = ser.take(x)
print(result)

Original Series
0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64
4    50
5    60
6    70
dtype: int64


In [32]:
# Write a pandas program to get the positions of items of a given series in another given series
import pandas as pd
series1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
series2 = pd.Series([1,3,5,7,10])
print("Original Series")
print(series1)
print('\n',series2)
result = [pd.Index(series1).get_loc(i) for i in series2]
print('\n')
print(result)

Original Series
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

 0     1
1     3
2     5
3     7
4    10
dtype: int64


[0, 2, 4, 6, 9]


In [36]:
# write a pandas program to convert the first and last character of each word's first character and Last character
# TO UPPER CASE
import pandas as pd
series1 = pd.Series(['php','python','java','c#','jeet','shah','raj','avi','doshi'])
print("Original Series")
print(series1)
result = series1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
print("Converting the First and last character of Each Word")
print(result)

Original Series
0       php
1    python
2      java
3        c#
4      jeet
5      shah
6       raj
7       avi
8     doshi
dtype: object
Converting the First and last character of Each Word
0       PhP
1    PythoN
2      JavA
3        C#
4      JeeT
5      ShaH
6       RaJ
7       AvI
8     DoshI
dtype: object


In [40]:
# Write a pandas program to calculate the number of character of each word

import pandas as pd
result = series1.map(lambda x: len(x))
print(result)

0    3
1    6
2    4
3    2
4    4
5    4
6    3
7    3
8    5
dtype: int64


In [44]:
# Write a pandas program to compute difference between consecutive numbers of a given series.

import pandas as pd

original_series = pd.Series([1,3,5,8,10,11,15])
print("Original Series")
print(original_series)
print("\n Difference of differences between two consecutive numbers of the said series")
print(original_series.diff().tolist())
print(original_series.diff().diff().tolist())

Original Series
0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64

 Difference of differences between two consecutive numbers of the said series
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [62]:
# Write a pandas program to convert a series of Date strings to a time Series
import pandas as pd
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
print("Original Series")
print(date_series)
print("Converted a Series of Date strings to TIME series")
print(pd.to_datetime(date_series,format='mixed'))

Original Series
0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object
Converted a Series of Date strings to TIME series
0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]


In [63]:
# Write a pandas program to get the day of month, day of year, week number and day of week.
import pandas as pd
from dateutil.parser import parse

date_series = date_series.map(lambda x: parse(x))
print("Original Date Series")
print(date_series)
print("Day of the Month")
print(date_series.dt.day.tolist())
print("Day of the Year")
# print(date_series.dt.dayofyear.tolist())
print("Week Number")

print("Day of Week")
print(date_series.dt.weekday_name.tolist())


Original Date Series
0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]
Day of the Month
[1, 2, 7, 6, 12, 6]
Day of the Year
Week Number
Day of Week


AttributeError: 'DatetimeProperties' object has no attribute 'weekday_name'

In [64]:
# Write a Pandas Program to convert year-month string to dates adding a specified day of the month

import pandas as pd
from dateutil.parser import parse
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series")
print(date_series)
print("\n New Dates")
result = date_series.map(lambda d: parse('11'+d))
print(result)

Original Series
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

 New Dates
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


In [77]:
# Write a Pandas program to filter words from a given series that contain atleast two vowels.
import pandas as pd
from collections import Counter
color_series = pd.Series(['Red','Green','Orange','Pink','Yellow'])
print('Filtered Words')
result = color_series.map(lambda c: sum([Counter(c.lower()).get(i,0) for i in list('aeiou')])>=2)
print(color_series[result])

Filtered Words
1     Green
2    Orange
4    Yellow
dtype: object


In [79]:
filtered_words = color_series[color_series.str.lower().str.count('[aeiou]') >= 2]
print(filtered_words)

1     Green
2    Orange
4    Yellow
dtype: object


In [83]:
# Write pandas program to compute the Euclidean desitance between two given series.
import pandas as pd
import numpy as np
x = pd.Series([1,2,3,4,5,6,7,8,9,10])
y = pd.Series([11,8,7,5,6,5,3,4,7,1])
print('Euclidean Distance between two said series')
print(np.linalg.norm(x-y))

Euclidean Distance between two said series
16.492422502470642


In [87]:
# Write a pandas program to find the position of the values neightbourhood by smaller values on both sides in a given series.
import pandas as pd
import numpy as np

num = pd.Series([1,8,7,5,6,-2,3,-1,7,1])

temp = np.diff(np.sign(np.diff(num)))
result = np.where(temp==-2)[0] + 1
print(result)

[1 4 6 8]


In [88]:
# pandas program to replace missing white spaces in a given string with the least frequent character
import pandas as pd

str1 = 'abc def abcdef icd'
print('Original Series')
ser = pd.Series(list(str1))
element_freq = ser.value_counts()
print(element_freq)
current_freq = element_freq.dropna().index[-1]
result = "".join(ser.replace(' ',current_freq))
print(result)

Original Series
c    3
     3
d    3
a    2
b    2
e    2
f    2
i    1
Name: count, dtype: int64
abcidefiabcdefiicd


In [90]:
# Write a pandas program to compute the autocorrelation of a given numeric series
import pandas as pd
import numpy as np
num_series = pd.Series(np.arange(15) + np.random.normal(1,10,15))
autocorelations = [num_series.autocorr(i).round(2) for i in range(11)]
print(autocorelations)

[1.0, 0.11, -0.2, -0.05, -0.38, -0.08, 0.12, -0.2, 0.1, 0.63, 0.77]


In [104]:
# Write a python program to convert given series into a dataframe with its index as another column on the data frame

import pandas as pd
import numpy as np
char_list = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
num_arra = np.arange(8)
num_dict = dict(zip(char_list,num_arra))
num_ser = pd.Series(num_dict)
df = num_ser.to_frame().reset_index()
print(df.head())

  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4


In [105]:
# Write a Pandas Program to find the index of the first occurence of the smallest and largest value of a given series

nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print("Original Series")
print(nums)
print("Index of the smallest and the largest number in the series")
print(nums.idxmin())
print(nums.idxmax())

Original Series
0     1
1     3
2     7
3    12
4    88
5    23
6     3
7     1
8     9
9     0
dtype: int64
Index of the smallest and the largest number in the series
9
4


# Pandas Data Frame Exercises

In [106]:
# write a pandas program to create a dataframe from a dictionary and display it
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [110]:
# dictonary data to dataframe using pandas

exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index= labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [118]:
#  Write a program to get the first 3 rows of a given DataFrame
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print("First Three Rows of the Data Frame")

print(df.iloc[0:3])

First Three Rows of the Data Frame
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
