# NUMPY

In [5]:
# importing numpy libraries
import numpy as np

In [6]:
l = [2,3.4,5,10,11]
a = numpy.array([2,3,4,5,202])

print(a)
print(type(a))

[  2   3   4   5 202]
<class 'numpy.ndarray'>


In [7]:
twod = np.array([[22,32,3,23,4],[23,2,34,4,3]])

In [8]:
print(twod)

[[22 32  3 23  4]
 [23  2 34  4  3]]


In [3]:
threed = np.array([[[22,32,3,23,4],[2,2,342,45,23],[234,234,32,423,54]],
                   [[22,32,3,23,4],[2,2,342,45,23],[234,234,32,423,54]],
                   [[22,32,3,23,4],[2,2,342,45,23],[234,234,32,423,54]]])
print(threed)
print("dimension:",threed.ndim)

[[[ 22  32   3  23   4]
  [  2   2 342  45  23]
  [234 234  32 423  54]]

 [[ 22  32   3  23   4]
  [  2   2 342  45  23]
  [234 234  32 423  54]]

 [[ 22  32   3  23   4]
  [  2   2 342  45  23]
  [234 234  32 423  54]]]
dimension: 3


In [17]:
seven = np.array([[[[[[[23,45,12,32]]]]]]])
print("dimension:",seven.ndim)

dimension: 7


In [19]:
ten = np.array([1,2,3,4,5,6,7,8],ndmin =10)
print("dimension:",ten.ndim)

dimension: 10


## Indexing and Slicing

In [20]:
import numpy as np
a = np.array([2,3,4,5,232])
twod = np.array([[22,32,3,23,4],[23,23,34,234,856],[83,2,32,76,45]])

In [21]:
print(a[0])
print(twod[1][2])

2
34


In [22]:
print(threed[1:3,0:1,0:2])

[[[22 32]]

 [[22 32]]]


## Copy and View

### Copy

In [24]:
import numpy as np
a = np.array([2,32,43,44])
c = a.copy()
c[0] = 555
print(a)
print(c)

[ 2 32 43 44]
[555  32  43  44]


### View

In [27]:
a = np.array([23,231,1,3345])
v = a.view()
v[0]= 69
print(a)

[  69  231    1 3345]


## Shape

In [28]:
twod

array([[ 22,  32,   3,  23,   4],
       [ 23,  23,  34, 234, 856],
       [ 83,   2,  32,  76,  45]])

In [30]:
twod.shape

(3, 5)

In [31]:
threed.shape

(3, 3, 5)

In [32]:
tend = np.array([2.2,23,2,3],ndmin=10)
print(tend)
print(tend.shape)

[[[[[[[[[[ 2.2 23.   2.   3. ]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


## Reshape

In [34]:
print(threed)
print("dimension:",threed.ndim)

[[[ 22  32   3  23   4]
  [  2   2 342  45  23]
  [234 234  32 423  54]]

 [[ 22  32   3  23   4]
  [  2   2 342  45  23]
  [234 234  32 423  54]]

 [[ 22  32   3  23   4]
  [  2   2 342  45  23]
  [234 234  32 423  54]]]
dimension: 3


In [35]:
threed.reshape(-1)

array([ 22,  32,   3,  23,   4,   2,   2, 342,  45,  23, 234, 234,  32,
       423,  54,  22,  32,   3,  23,   4,   2,   2, 342,  45,  23, 234,
       234,  32, 423,  54,  22,  32,   3,  23,   4,   2,   2, 342,  45,
        23, 234, 234,  32, 423,  54])

In [36]:
threed.shape

(3, 3, 5)

In [37]:
threed.reshape(3,5,-1)

array([[[ 22,  32,   3],
        [ 23,   4,   2],
        [  2, 342,  45],
        [ 23, 234, 234],
        [ 32, 423,  54]],

       [[ 22,  32,   3],
        [ 23,   4,   2],
        [  2, 342,  45],
        [ 23, 234, 234],
        [ 32, 423,  54]],

       [[ 22,  32,   3],
        [ 23,   4,   2],
        [  2, 342,  45],
        [ 23, 234, 234],
        [ 32, 423,  54]]])

In [40]:
threed.reshape(3,5,3)

array([[[ 22,  32,   3],
        [ 23,   4,   2],
        [  2, 342,  45],
        [ 23, 234, 234],
        [ 32, 423,  54]],

       [[ 22,  32,   3],
        [ 23,   4,   2],
        [  2, 342,  45],
        [ 23, 234, 234],
        [ 32, 423,  54]],

       [[ 22,  32,   3],
        [ 23,   4,   2],
        [  2, 342,  45],
        [ 23, 234, 234],
        [ 32, 423,  54]]])

## ITERATION IN NUMPY

In [4]:
import numpy as np
for x in np.nditer(threed):
    print(x)

22
32
3
23
4
2
2
342
45
23
234
234
32
423
54
22
32
3
23
4
2
2
342
45
23
234
234
32
423
54
22
32
3
23
4
2
2
342
45
23
234
234
32
423
54


### Task 1 : zeros and ones

In [131]:
chex = np.zeros((8,8))
print(chex)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [107]:
chex1 = np.ones((8,8))
print(chex1)
print(chex1.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
2


In [134]:
for i in range(8):
    if i%2==0:
        for j in range(8):
            if j%2 != 0:
                chex[i][j]=1
    elif i%2 !=0:
        for j in range(8):
            if j%2 ==0:
                chex[i][j]=1
                

In [135]:
print(chex)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [127]:
print(0%2!=0)

False


### Transpose matrix

In [ ]:
#importing packages

import numpy as np