In [81]:
import numpy as np
from numpy import random

###### Test whether two arrays are element-wise equal within a tolerance

In [48]:

import numpy as np
from numpy import random

array1 = random.rand(1,5)
array2 = random.rand(1,5)

# Define a tolerance value
tolerance = 1.05

# Check if arrays are element-wise equal within the tolerance
result = np.allclose(array1, array2, rtol=tolerance)

if result:
    print("Arrays are element-wise equal within the tolerance.")
else:
    print("Arrays are not element-wise equal within the tolerance.")


Arrays are element-wise equal within the tolerance.


###### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [56]:
import numpy as np
from numpy import random
arr1 = random.randint(10,size =10)
arr2 = random.randint(10,size =10)
x = np.array(arr1)
y = np.array(arr2)
print("Original array")
print(x)
print(y)
print("Greater Than")
print(np.greater(x,y))
print("Greater Than Equal")
print(np.greater_equal(x,y))
print("Less Than")
print(np.less(x,y))
print("Less than Equal To")
print(np.less_equal(x,y))

Original array
[3 6 2 3 9 6 8 2 9 3]
[3 0 8 2 3 0 4 2 0 4]
Greater Than
[False  True False  True  True  True  True False  True False]
Greater Than Equal
[ True  True False  True  True  True  True  True  True False]
Less Than
[False False  True False False False False False False  True]
Less than Equal To
[ True False  True False False False False  True False  True]


###### Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array 

In [57]:
import numpy as np
X = np.array([1, 7, 13, 105])
print("Original Array")
print(X)
print("Memory occupied")
print("%d bytes"%(X.size * X.itemsize))

Original Array
[  1   7  13 105]
Memory occupied
16 bytes


###### Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [65]:
import numpy as np
arr_zeros = np.zeros(10)
print("Aray of 10 Zeros")
print(arr_zeros)
arr_ones = np.ones(10)
print("Array of 10 ones")
print(arr_ones)
arr_fives = np.ones(10)*5
print("Array of 10 Fives")
print(arr_fives)

Aray of 10 Zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 10 Fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


###### Write a NumPy program to create an array of integers from 30 to 70

In [69]:
import numpy as np
array = np.arange(30,71)

print("Printing Array from Range(30 to 70):",array)

Printing Array from Range(30 to 70): [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


###### Write a NumPy program to create an array of all even integers from 30 to 70.

In [70]:
import numpy as np
arr1 = np.arange(30,71,2)
print("Array from range(30 to 70) EVEN",arr1)

Array from range(30 to 70) EVEN [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


###### Write a NumPy program to create a 3x3 identity matrix

In [73]:
import numpy as np
A = random.randint(10,size=(3,3))
print(A)

[[3 6 3]
 [4 3 2]
 [4 1 4]]


###### Write a NumPy program to generate a random number between 0 and 1

In [80]:
import numpy as np
from numpy import random
r_num = random.randint(2,size=1)
print(r_num)

[0]


###### Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [84]:
normal = random.normal(1,2,size=15)
print("Standard Normal Distribution")
print(normal)

Standard Normal Distribution
[ 1.60869239 -0.23220683 -1.26442497  3.71054105  1.61162503  1.4418064
  3.5256992   0.56979656  2.07039174 -0.05142473 -0.30432492  3.72015853
  1.39919565 -0.45064404  0.60565814]


###### Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [86]:
arr_vector = np.arange(15,56)
print("Original Array")
print(arr_vector)
print("Array Except first and last element")
print(arr_vector[1:-1])

Original Array
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Array Except first and last element
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


###### Write a NumPy program to create a 3X4 array and iterate over it

In [93]:
array = random.randint(100,size=(3,4))
print("Original Array: ")
print(array)
print("Iterated Array: ")
for i in np.nditer(array):
    print(i)

Original Array: 
[[94 47 81 93]
 [23  5 93 74]
 [79 89 47 85]]
Iterated Array: 
94
47
81
93
23
5
93
74
79
89
47
85


###### Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [108]:
a1 = np.linspace(5,50,10)
print(a1)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


###### Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [112]:
B = random.randint(20,size=20)
print("Original Array")
print(B)
B[(B>=9)&(B<=15)] *=-1
print("Changed Vector Array")
print(B)

Original Array
[ 9  3  9  8 17 12 13 17 17  5 17  5  5 12 18 14  9  9  5  2]
Changed Vector Array
[ -9   3  -9   8  17 -12 -13  17  17   5  17   5   5 -12  18 -14  -9  -9
   5   2]


###### Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [114]:
C = random.randint(0,11,size=5)
print(C)

[ 9  1  0 10  9]


###### Write a NumPy program to multiply the values of two given vectors.


In [115]:
x = random.randint(1,5,5)
y = random.randint(5,10,5)
print("Original Array")
print(x)
print(y)
print("Multiplied Array")
print(x*y)


Original Array
[2 4 1 3 2]
[9 6 8 7 8]
Multiplied Array
[18 24  8 21 16]


###### Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [118]:
mat = random.randint(10,21,size=(3,4))
print(mat)

[[15 19 13 14]
 [14 14 13 20]
 [19 19 13 19]]


###### Write a NumPy program to find the number of rows and columns in a given matrix.

In [124]:
s = random.randint(4,10,size=(3,4))
print(s)
print("Row = ",s.shape[0],"Column =",s.shape[1])

[[5 4 6 6]
 [9 4 8 5]
 [5 9 9 4]]
Row =  3 Column = 4


###### Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0

In [217]:
matrix = np.zeros((3,3))
print("Original Array")
print(matrix)
for i in range(len(matrix)):
    
    for j in range(len(matrix[i])):
        if i==j:
            matrix[i][j]=1
print("Diagonally printing Ones")
print(matrix)
            

Original Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Diagonally printing Ones
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###### Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [238]:
ones = np.zeros((10,10))
x =len(ones)
for i in range(len(ones)):
    for j in range(len(ones[i])):
        if j==0:
            ones[i][j]=1
        if j==x-1:
            ones[i][j]=1
        if i==x-1:
            ones[i][j]=1
        if i==0:
            ones[i][j]=1
print(ones)

                 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
10


In [240]:
ones = np.zeros((6,6))
x =len(ones)
for i in range(len(ones)):
    for j in range(len(ones[i])):
        if j==0:
            ones[i][j]=1
        if j==x-1:
            ones[i][j]=1
        if i==x-1:
            ones[i][j]=1
        if i==0:
            ones[i][j]=1
print(ones)

   

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [241]:
#Second Method

x = np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###### Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.



In [243]:
x = np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [245]:
x = np.zeros((4,4))
x[::2,1::2]=1
x[1::2,::2]=1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


###### Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [248]:
x = np.random.random((3,3,3))
print(x)

[[[0.3998958  0.75417859 0.88751052]
  [0.24108097 0.01570386 0.35343446]
  [0.00298049 0.16091618 0.16680575]]

 [[0.79687764 0.52044367 0.48544188]
  [0.30526776 0.51869981 0.75152944]
  [0.98573733 0.64972952 0.47433426]]

 [[0.88477819 0.09063385 0.51099165]
  [0.88230238 0.03507977 0.34326973]
  [0.90715698 0.20841189 0.28869741]]]


###### Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array

In [257]:
x = random.randint(10,size=(3,3))

print("Original Array")
print(x)

print("Sum of all elements")
print(np.sum(x))
print("Sum of all Columns")
print(np.sum(x,axis=0))
print("Sum of Each Row")
print(np.sum(x,axis=1))

Original Array
[[7 1 1]
 [3 3 8]
 [3 8 4]]
Sum of all elements
38
Sum of all Columns
[13 12 13]
Sum of Each Row
[ 9 14 15]


###### Write a NumPy program to compute the inner product of two given vectors

In [273]:
x = random.randint(10,size=2)
y = random.randint(10,size=2)
print(x,y)
print("Inner Product of said Vectors:")
print(np.dot(x,y))
#dot function is used to product the vector.


[8 0] [0 0]
Inner Product of said Vectors:
0


###### Write a NumPy program to add a vector to each row of a given matrix

In [276]:
# empty_like() function refers to the one matrix or vector we want to copy but not the data just the size
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([3,2,9])

result = np.empty_like(m)

for i in range(4):
    result[i,:]=m[i,:]+v
print(result)

[[ 4  4 12]
 [ 7  7 15]
 [10 10 18]
 [13 13 21]]


###### Write a NumPy program to save a given array to a binary file

In [279]:
import numpy as np
import os
a = np.arange(20)
np.save('temp_array.npy',a)
print("Check if 'temp_arra.npy' exists or not?")

if os.path.exists('temp_array.npy'):
    x2 = np.load('temp_array.npy')
    print(np.array_equal(a, x2))

Check if 'temp_arra.npy' exists or not?
True


In [289]:
import numpy as np

import os

# Creating a NumPy array 'x' containing integers from 0 to 9 using np.arange()
x = np.arange(10)

# Creating a NumPy array 'y' containing integers from 11 to 19 using np.arange()
y = np.arange(11, 20)

# Printing a message indicating the original arrays 'x' and 'y'
print("Original arrays:")
print(x)
print(y)

# Saving the arrays 'x' and 'y' into a '.npz' file named 'temp_arra.npz' using np.savez()
np.savez('temp_arra.npz', x=x, y=y)

# Printing a message indicating loading arrays from the 'temp_arra.npz' file
print("Load arrays from the 'temp_arra.npz' file:")

# Loading data from 'temp_arra.npz' into variables 'x2' and 'y2' using np.load()
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    
    # Printing the loaded arrays 'x2' and 'y2'
    print(x2)
    print(y2) 


Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


###### Write a NumPy program to save a given array to a text file and load it

In [293]:
import numpy as np
import os
x = np.arange(12).reshape(4,3)

print(x)
head = 'col1 col2 col3'
np.savetxt('temp.txt',x,fmt="%d",header=head)
result = np.loadtxt('temp.txt')
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


###### Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.

In [313]:
x = random.randint(3,size=(4,3))
a = 0
print(x)
for i in range(len(x)):
    for j in range(len(x[i])):
        if x[i][j] ==0  and i< len(x)-1:
            x[i+1][j] = 0
        a += x[i][j]
        print(a)
print("sum",a)
                              

[[2 0 0]
 [1 2 0]
 [0 1 2]
 [2 0 2]]
2
2
2
3
3
3
3
3
3
3
3
3
sum 3


###### Write a NumPy program to find missing data in a given array

In [326]:
# Importing the NumPy library with an alias 'np'
import numpy as np
 
nums = random.random(size=10)
for i in range(len(nums)):
    if nums[i]==0:
        nums[i]=np.nan
print(nums)
               

[0.60989858 0.83799334 0.16759689 0.29213821 0.94602585 0.38546335
 0.72314783 0.32523141 0.8761962  0.22018367]
