In [2]:
import numpy as np

###### Write a numpy program to find missing values

In [8]:
x = np.array([1,2,np.nan,3,4,np.nan,5,np.nan])
print(x)
print(np.isnan(x))

[ 1.  2. nan  3.  4. nan  5. nan]
[False False  True False False  True False  True]


###### Numpy program to check if two arrays are equal

In [13]:
import numpy as np

nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])

np.set_printoptions(precision=10)

# Printing a message indicating the original arrays 'nums1' and 'nums2'
print("Original arrays:")
print(nums1)
print(nums2)

# Printing a message asking whether the two arrays are equal element-wise or not
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)

# Reassigning new values to arrays 'nums1' and 'nums2'
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])

# Printing a message indicating the original arrays 'nums1' and 'nums2'
print("\nOriginal arrays:")
np.set_printoptions(precision=1)
print(nums1)
print(nums2)

# Printing a message asking whether the two arrays are equal element-wise or not
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2)) 


Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5 1.5 0.2]
[0.5 1.5 0.2]

Test said two arrays are equal (element wise) or not:?
[False False  True]


###### Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros

In [17]:
x = np.zeros((5,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


###### Write a NumPy program to sort a given array by row and column in ascending order.

In [19]:
b = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])

In [22]:
print(b)
print(np.sort(b))
print(np.sort(b,axis=0))

[[5.5 3.4 8. ]
 [3.5 4.4 7. ]
 [1.5 2.4 9.3]]
[[3.4 5.5 8. ]
 [3.5 4.4 7. ]
 [1.5 2.4 9.3]]
[[1.5 2.4 7. ]
 [3.5 3.4 8. ]
 [5.5 4.4 9.3]]


###### Write a NumPy program to extract all numbers from a given array less and greater than a specified number.

In [23]:
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])

In [25]:
print("Original array:")
print(nums)
n = 8.32
r = 18.32
# Printing a message indicating the replacement of elements equal to 'n' with 'r'
print("\nReplace elements of the said array which are equal to", n, "with", r)
print(np.where(nums == n, r, nums))

# Printing a message indicating the replacement of elements less than 'n' with 'r'
print("\nReplace elements of the said array which are less than", n, "with", r)
print(np.where(nums < n, r, nums))

# Printing a message indicating the replacement of elements greater than 'n' with 'r'
print("\nReplace elements of the said array which are greater than", n, "with", r)
print(np.where(nums > n, r, nums)) 

Original array:
[[5.5 3.4 8. ]
 [3.5 8.3 7. ]
 [1.5 2.4 9.3]]

Replace elements of the said array which are equal to 8.32 with 18.32
[[ 5.5  3.4  8. ]
 [ 3.5 18.3  7. ]
 [ 1.5  2.4  9.3]]

Replace elements of the said array which are less than 8.32 with 18.32
[[18.3 18.3 18.3]
 [18.3  8.3 18.3]
 [18.3 18.3  9.3]]

Replace elements of the said array which are greater than 8.32 with 18.32
[[ 5.5  3.4  8. ]
 [ 3.5  8.3  7. ]
 [ 1.5  2.4 18.3]]


###### Write a NumPy program to swap rows and columns of a given array in reverse order.

In [27]:
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
new_nums = nums[::-1, ::-1]
print(new_nums) 


[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


###### numpy program to create 3x3 matrix with values ranging from 2 to 10


In [30]:
nums = np.arange(2,11).reshape(3,3)
print(nums)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


###### Extract all the rows to compute the student weight from a given array (student information) where a specific column starts with a given character

In [46]:
# Importing NumPy library
import numpy as np

# Setting printing options to display arrays with a maximum line width of 100
np.set_printoptions(linewidth=100)

# Creating a NumPy array containing student data with IDs, class, names, and weights
student = np.array([
    ['01', 'V', 'Debby Pramod', 30.21],
    ['02', 'V', 'Artemiy Ellie', 29.32],
    ['03', 'V', 'Baptist Kamal', 31.00],
    ['04', 'V', 'Lavanya Davide', 30.22],
    ['05', 'V', 'Fulton Antwan', 30.21],
    ['06', 'V', 'Euanthe Sandeep', 31.00],
    ['07', 'V', 'Endzela Sanda', 32.00],
    ['08', 'V', 'Victoire Waman', 29.21],
    ['09', 'V', 'Briar Nur', 30.00],
    ['10', 'V', 'Rose Lykos', 32.00]
])

# Displaying the original array
print("Original array:")
print(student)

# Finding the total weight of students whose names start with a specific character ('E')
char = 'E'
result = student[np.char.startswith(student[:,2], char)]
print("\nTotal weight, where student name starts with", char)
print(np.round(result[:, 3].astype(float).sum(), 2))



Original array:
[['01' 'V' 'Debby Pramod' '30.21']
 ['02' 'V' 'Artemiy Ellie' '29.32']
 ['03' 'V' 'Baptist Kamal' '31.0']
 ['04' 'V' 'Lavanya Davide' '30.22']
 ['05' 'V' 'Fulton Antwan' '30.21']
 ['06' 'V' 'Euanthe Sandeep' '31.0']
 ['07' 'V' 'Endzela Sanda' '32.0']
 ['08' 'V' 'Victoire Waman' '29.21']
 ['09' 'V' 'Briar Nur' '30.0']
 ['10' 'V' 'Rose Lykos' '32.0']]

Total weight, where student name starts with E
63.0


#### Linear Algebra in Python

In [48]:
def al(x):
    return (2*x+3)

print(al(2))

7
