In [10]:
import numpy as np

# Numpy Dates and Time

###### Write a NumPy program to display all the dates for the month of March, 2017.

In [6]:
import numpy as np
print("March , 2017")
print(np.arange("2017-03","2017-04",dtype="datetime64[D]"))

March , 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


###### Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [7]:
import numpy as np

yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yesterday: ",yesterday)
today = np.datetime64('today','D')
print("Today: ",today)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2023-12-18
Today:  2023-12-19
Tomorrow:  2023-12-20


###### Write a NumPy program to count the number of days of specific month.

In [9]:
import numpy as np

print("Number of days in February, 2016")
print(np.datetime64('2016-03-01')-np.datetime64('2016-02-01'))
print("Number of days in Feb, 2017")
print(np.datetime64('2017-03-01')-np.datetime64('2017-02-01'))

Number of days in February, 2016
29 days
Number of days in Feb, 2017
28 days


###### Write a NumPy program to find the first monday in March, 2017



In [16]:
import numpy as np
print("First Monday in Jan, 2024")
print(np.busday_offset('2024-01',0,roll="forward",weekmask="Mon"))

First Monday in Jan, 2024
2024-01-01


###### Write a NumPy program to find the number of weekdays in March 2017

In [19]:
import numpy as np
print("Number of weekdays in March,2017")
print(np.busday_count('2017-03','2017-04'))

Number of weekdays in March,2017
23


###### Write a NumPy program to convert numpy datetime64 to Timestamp.



In [20]:
import numpy as np
from datetime import datetime

In [21]:
dt = datetime.utcnow()
print("Current Date")
print(dt)

Current Date
2023-12-19 06:40:51.170506


In [22]:
dt64 = np.datetime64(dt)

# Numpy Strings

##### Concatenate element-wise two arrays of string

In [31]:
# Importing the necessary library
import numpy as np

# Creating two NumPy arrays with string elements
x1 = np.array(['Python', 'PHP'])
x2 = np.array([' Java', ' C++'])

# Displaying the contents of Array1
print("Array1:")
print(x1)

# Displaying the contents of Array2
print("Array2:")
print(x2)

# Concatenating the strings element-wise between x1 and x2 using np.char.add function
new_array = np.char.add(x1, x2)

# Displaying the new array formed by concatenating elements from x1 and x2
print("New array:")
print(new_array)


Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
New array:
['Python Java' 'PHP C++']


##### Write a NumPy program to repeat all the elements three times of a given array of string.



In [38]:
X1 = np.array(['Python ','Php ','JAVA ',' C++' ])

print("Original Array: \n",X1)
new_arr = np.char.multiply(X1,3)
print(new_arr)

Original Array: 
 ['Python ' 'Php ' 'JAVA ' ' C++']
['Python Python Python ' 'Php Php Php ' 'JAVA JAVA JAVA ' ' C++ C++ C++']


##### Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [40]:
# Importing the necessary library
import numpy as np

# Creating a NumPy array containing strings
x = np.array(['python', 'PHP', 'java', 'C++'])

# Displaying the original array
print("Original Array:")
print(x)

# Applying various string manipulation functions from np.char module
# Capitalizing the first character of each string
capitalized_case = np.char.capitalize(x)

# Converting all characters to lowercase
lowered_case = np.char.lower(x)

# Converting all characters to uppercase
uppered_case = np.char.upper(x)

# Swapping the case of characters (lowercase to uppercase and vice versa)
swapcased_case = np.char.swapcase(x)

# Capitalizing the first character of each word in the string
titlecased_case = np.char.title(x)

# Displaying the modified arrays after applying string manipulation functions
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case) 

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


##### Write a NumPy program to insert a space between characters of all the elements of a given array.



In [44]:
import numpy as np
x = np.array(['python exercises','PHP','Java'])
print(x)
r = np.char.join(" ",x)
print(r)

['python exercises' 'PHP' 'Java']
['p y t h o n   e x e r c i s e s' 'P H P' 'J a v a']


##### Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.



In [45]:
import numpy as np
x = np.array([' Python Exercices',' Python ','  php  '])
print(x)
print('After Manipulation or Stripping')
stripped = np.char.strip(x)
print(stripped)

[' Python Exercices' ' Python ' '  php  ']
After Manipulation or Stripping
['Python Exercices' 'Python' 'php']


##### Write a NumPy program to remove the trailing whitespaces of all the elements of a given array.



In [49]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'])
print(x)
re = np.char.lstrip(x)
print(re)
#lstrip for left strip
#rstrip for trailing spaces(right strip)

[' python exercises ' ' PHP  ' ' java  ' '  C++']
['python exercises ' 'PHP  ' 'java  ' 'C++']


##### Write a NumPy program to split the element of a given array with spaces.



In [51]:
import numpy as np
x = np.array(['Python PHP Java C++','Jeet Vipul Shah'])

print('original array')
print(x)
r = np.char.split(x)
print(r)

original array
['Python PHP Java C++' 'Jeet Vipul Shah']
[list(['Python', 'PHP', 'Java', 'C++']) list(['Jeet', 'Vipul', 'Shah'])]


##### Write a numpy program to split the elements of a given array to multiple lines

In [55]:
x = np.array(['Python\nExercises, Practice, Solution'])
print(x)
r = np.char.splitlines(x)
print(r)

['Python\nExercises, Practice, Solution']
[list(['Python', 'Exercises, Practice, Solution'])]


##### Write a NumPy program to replace "PHP" with "Python" in the element of a given array.




In [57]:
# Importing necessary library
import numpy as np

# Creating a NumPy array containing a single string
x = np.array(['PHP Exercises, Practice, Solution'], dtype=np.str_)

# Displaying the original array
print("\nOriginal Array:")
print(x)

# Replacing "PHP" with "Python" in the string of the array
r = np.char.replace(x, "PHP", "Python")

# Displaying the updated array after replacing the substring
print("\nNew array:")
print(r) 



Original Array:
['PHP Exercises, Practice, Solution']

New array:
['Python Exercises, Practice, Solution']


##### Write a NumPy program to count the number of "P" in a given array, element-wise.



In [68]:
# Importing necessary library
import numpy as np

# Creating a NumPy array containing strings
x1 = np.array(["JEET","SHAH","JEEL","PATEL"], dtype=np.str_)

# Displaying the content of the original array
print("\nOriginal Array:")
print(x1)

# Counting the occurrences of the character 'P' in each string of the array x1
print("Number of ‘J’:")
r = np.char.count(x1, "J")
print(r) 



Original Array:
['JEET' 'SHAH' 'JEEL' 'PATEL']
Number of ‘J’:
[1 0 1 0]


#####  Write a NumPy program to split a given text into lines and split the single line into array values.

In [70]:
import numpy as np
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

print(student)

01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos


In [72]:
text_lines= student.splitlines()
text_lines = [r.split('\t') for r in text_lines]

result = np.array(text_lines)
print(result)

[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]


# Advance Numpy

##### Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element

In [76]:
import numpy as np
num = np.random.rand(5,5)
exp_arr = np.exp(num)
print("Original Array:")
print(num)
print("Exponential Array:")
print(exp_arr)

Original Array:
[[0.12981813 0.01973367 0.63103148 0.00471203 0.84449519]
 [0.75250004 0.72053477 0.23423815 0.20393413 0.75435351]
 [0.73686802 0.88339643 0.48113653 0.53796103 0.92017666]
 [0.12119857 0.26281534 0.16589122 0.69760614 0.63315197]
 [0.37579706 0.44004192 0.89690374 0.78783066 0.25083821]]
Exponential Array:
[[1.13862128 1.01992967 1.87954829 1.00472315 2.32680291]
 [2.12229922 2.05553216 1.26394546 1.22621738 2.12623649]
 [2.08938135 2.41910208 1.61791217 1.71251155 2.50973372]
 [1.12884905 1.30058653 1.18044469 2.00893782 1.88353809]
 [1.4561516  1.5527723  2.45199931 2.1986217  1.28510215]]


##### Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.



In [92]:
import numpy as np
num = np.random.rand(5,5)
print("Original Array:")
print(num)

min_val = num.min()
num[num==min_val]=0
print("Manipulated Array")
print(num)


Original Array:
[[0.97066533 0.24903124 0.38133826 0.95374125 0.93492523]
 [0.28670889 0.02794777 0.18910215 0.97107295 0.93646463]
 [0.94349883 0.68922852 0.65269805 0.54402837 0.49783195]
 [0.19319192 0.71717602 0.29335944 0.10776255 0.85171049]
 [0.26757416 0.02232909 0.57611168 0.83744205 0.79831632]]
Manipulated Array
[[0.97066533 0.24903124 0.38133826 0.95374125 0.93492523]
 [0.28670889 0.02794777 0.18910215 0.97107295 0.93646463]
 [0.94349883 0.68922852 0.65269805 0.54402837 0.49783195]
 [0.19319192 0.71717602 0.29335944 0.10776255 0.85171049]
 [0.26757416 0.         0.57611168 0.83744205 0.79831632]]


##### Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.

In [93]:
from numpy import *
import numpy as np
nums = np.random.rand(5,5)
print("Original Array:")
print(nums)
max = nums.max()
nums[nums==max]=0
print("Manipulated Array:")
print(nums)

Original Array:
[[0.51263339 0.19431526 0.12991366 0.00389778 0.66241778]
 [0.32230698 0.43770403 0.44166935 0.17366145 0.39261121]
 [0.12691783 0.38070904 0.26599083 0.52243808 0.93887463]
 [0.37490515 0.54422099 0.74013968 0.83027105 0.92991764]
 [0.36851719 0.17561646 0.26962111 0.82689395 0.78597702]]
Manipulated Array:
[[0.51263339 0.19431526 0.12991366 0.00389778 0.66241778]
 [0.32230698 0.43770403 0.44166935 0.17366145 0.39261121]
 [0.12691783 0.38070904 0.26599083 0.52243808 0.        ]
 [0.37490515 0.54422099 0.74013968 0.83027105 0.92991764]
 [0.36851719 0.17561646 0.26962111 0.82689395 0.78597702]]


##### Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [97]:
import numpy as np
# create a 5x5 array with random values
nums = np.random.rand(5, 5)
print("Original array elements:")
print(nums)
# find the indices of the second-largest value in each column
indices = np.argsort(nums, axis=0)[-2, :]
# get the second-largest value in each column using the indices
second_largest_values = nums[indices, np.arange(nums.shape[1])]
print("\nSecond-largest value in each column:")
print(second_largest_values)

Original array elements:
[[0.36841271 0.64277098 0.88726241 0.55258182 0.34482688]
 [0.89513964 0.89766687 0.24268637 0.07703571 0.67565814]
 [0.50053904 0.43547793 0.86381642 0.18373151 0.01288604]
 [0.34535455 0.640237   0.66646545 0.48863675 0.37633162]
 [0.96920595 0.97667804 0.23470698 0.3804641  0.58225258]]

Second-largest value in each column:
[0.89513964 0.89766687 0.86381642 0.48863675 0.58225258]


##### Write a NumPy program to create a 5x5 array with random values and sort each column



In [101]:
import numpy as np
b = np.random.rand(5,5)
print("Original Array")
print(b)
print("Sorted by Each Column")
print(np.sort(b,axis=0))

Original Array
[[0.65838399 0.37435401 0.29455761 0.32925949 0.01433632]
 [0.42479836 0.39471979 0.74286767 0.47252324 0.87902148]
 [0.97338805 0.89168097 0.9013055  0.11540919 0.69010109]
 [0.29362687 0.85199299 0.16558355 0.05527284 0.75685765]
 [0.94126998 0.54661047 0.66616853 0.61718137 0.17148449]]
Sorted by Each Column
[[0.29362687 0.37435401 0.16558355 0.05527284 0.01433632]
 [0.42479836 0.39471979 0.29455761 0.11540919 0.17148449]
 [0.65838399 0.54661047 0.66616853 0.32925949 0.69010109]
 [0.94126998 0.85199299 0.74286767 0.47252324 0.75685765]
 [0.97338805 0.89168097 0.9013055  0.61718137 0.87902148]]


##### Write a NumPy program to create a 5x5 array with random values and sort each row.


In [105]:
import numpy as np
num_row = np.random.rand(5,5)
print("Original Array: \n",num_row)
print("Sorted by Each Row")
print(np.sort(num_row,axis=1))

Original Array: 
 [[0.93587233 0.76679568 0.3780192  0.62380321 0.98904581]
 [0.65773717 0.36453939 0.1266744  0.99886697 0.76127902]
 [0.40346036 0.72128524 0.84931726 0.61101669 0.00374173]
 [0.38000903 0.21162474 0.75480478 0.25465002 0.43858346]
 [0.10127104 0.53790528 0.81211441 0.20926242 0.33667773]]
Sorted by Each Row
[[0.3780192  0.62380321 0.76679568 0.93587233 0.98904581]
 [0.1266744  0.36453939 0.65773717 0.76127902 0.99886697]
 [0.00374173 0.40346036 0.61101669 0.72128524 0.84931726]
 [0.21162474 0.25465002 0.38000903 0.43858346 0.75480478]
 [0.10127104 0.20926242 0.33667773 0.53790528 0.81211441]]


##### Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.

In [107]:
import numpy as np
nu = np.random.rand(3,3,3)
print("Original Array Elements:")
print(nu)
sum_ = np.sum(nu,axis=2)
print("Sum along the last axis:")
print(sum_)

Original Array Elements:
[[[0.41294514 0.64063041 0.84765972]
  [0.01921907 0.91917076 0.05097481]
  [0.29050738 0.45887395 0.65629804]]

 [[0.63509431 0.72942181 0.71980582]
  [0.06959961 0.45522172 0.7771103 ]
  [0.81849606 0.9122342  0.57051318]]

 [[0.56244859 0.31522438 0.27422339]
  [0.01125473 0.06343001 0.30695868]
  [0.25062399 0.80050853 0.00130285]]]
Sum along the last axis:
[[1.90123527 0.98936464 1.40567936]
 [2.08432194 1.30193163 2.30124344]
 [1.15189635 0.38164342 1.05243537]]


##### Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.

In [109]:
import numpy as np
nums = np.random.rand(5,5)
print("Original Array Element")
print(nums)
col_means = np.mean(nums,axis=0)

arr_normalized = (nums - col_means)/np.std(nums,axis=0)
print("Original Array:\n",nums)
print("\nNormalized Array:\n",arr_normalized)

Original Array Element
[[0.1472387  0.34435996 0.69715361 0.93188962 0.42310731]
 [0.22341353 0.73894979 0.26537076 0.80418753 0.15698184]
 [0.71145817 0.74991981 0.57136738 0.47632449 0.20706237]
 [0.25440894 0.82907617 0.15763733 0.24852991 0.66646735]
 [0.91030728 0.01170898 0.94748866 0.4807003  0.61658908]]
Original Array:
 [[0.1472387  0.34435996 0.69715361 0.93188962 0.42310731]
 [0.22341353 0.73894979 0.26537076 0.80418753 0.15698184]
 [0.71145817 0.74991981 0.57136738 0.47632449 0.20706237]
 [0.25440894 0.82907617 0.15763733 0.24852991 0.66646735]
 [0.91030728 0.01170898 0.94748866 0.4807003  0.61658908]]

Normalized Array:
 [[-0.99445883 -0.61182651  0.58952489  1.3928264   0.04384677]
 [-0.74372709  0.65585224 -0.91355539  0.87511431 -1.24328165]
 [ 0.86268644  0.69109505  0.15165017 -0.45406245 -1.0010648 ]
 [-0.64170478  0.94539668 -1.28858649 -1.37755559  1.22086915]
 [ 1.51720425 -1.68051746  1.46096682 -0.43632266  0.97963053]]


##### 6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.


In [111]:
import numpy as np
nums = np.random.rand(5,5)
print("Original Array Element")
print(nums)
col_means = np.mean(nums,axis=0)

arr_normalized = (nums - col_means)/np.std(nums,axis=1)
print("Original Array:\n",nums)
print("\nNormalized Array:\n",arr_normalized)

Original Array Element
[[0.37963399 0.5529023  0.71905905 0.87656881 0.28577316]
 [0.83372058 0.90778944 0.31111737 0.56296867 0.64978333]
 [0.10897307 0.52186992 0.15644558 0.17575482 0.05746481]
 [0.45734227 0.07159472 0.57953454 0.05455421 0.16972336]
 [0.74003953 0.48871707 0.01413797 0.01774517 0.81888781]]
Original Array:
 [[0.37963399 0.5529023  0.71905905 0.87656881 0.28577316]
 [0.83372058 0.90778944 0.31111737 0.56296867 0.64978333]
 [0.10897307 0.52186992 0.15644558 0.17575482 0.05746481]
 [0.45734227 0.07159472 0.57953454 0.05455421 0.16972336]
 [0.74003953 0.48871707 0.01413797 0.01774517 0.81888781]]

Normalized Array:
 [[-0.57552495  0.21009655  2.21240299  2.53163976 -0.32109718]
 [ 1.52682068  1.89213086 -0.27390836  1.05882296  0.73615394]
 [-1.82864016  0.06301448 -1.2165976  -0.75971913 -0.98420846]
 [-0.21574852 -2.0711241   1.36203297 -1.32893535 -0.65815857]
 [ 1.09309295 -0.0941178  -2.08393    -1.50180824  1.22731027]]
