In [13]:
# 50. Write a Pandas program to sort a given DataFrame by two or more columns.
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, 12.2, 9, 20, 14.5, 15.2, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data)
print("Original DataFrame")
print(df)
print("Sorting Values using Attempts and Name")
df = df.sort_values(['attempts','name'], ascending=[True,True])
print(df)

Original DataFrame
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James   12.2         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura   15.2         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes
Sorting Values using Attempts and Name
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
9      Jonas   19.0         1     yes
7      Laura   15.2         1      no
6    Matthew   14.5         1     yes
4      Emily    9.0         2      no
2  Katherine   16.5         2     yes
8      Kevin    8.0         2      no
1       Dima    9.0         3      no
3      James   12.2         3      no
5    Michael   20.0         3     yes


In [15]:
#51 Write a Pandas program to convert the datatype of a given column(floats to ints).
import pandas as pd

print(df.dtypes)

df.score = df.score.astype(int)
print(df)
print(df.dtypes)

name        object
score        int32
attempts     int64
qualify     object
dtype: object
        name  score  attempts qualify
0  Anastasia     12         1     yes
9      Jonas     19         1     yes
7      Laura     15         1      no
6    Matthew     14         1     yes
4      Emily      9         2      no
2  Katherine     16         2     yes
8      Kevin      8         2      no
1       Dima      9         3      no
3      James     12         3      no
5    Michael     20         3     yes
name        object
score        int32
attempts     int64
qualify     object
dtype: object


In [16]:
# Datetime Series Example and Test

import pandas as pd
import numpy as np
pdt = pd.date_range(start="2024-01-22",end="2029-01-22",freq="D")
# print(len(pdt))
v = np.random.random(size=len(pdt))
df = pd.DataFrame({"value": v},index=pdt)
print(df)

               value
2024-01-22  0.321041
2024-01-23  0.667199
2024-01-24  0.008505
2024-01-25  0.283320
2024-01-26  0.984259
...              ...
2029-01-18  0.310093
2029-01-19  0.459313
2029-01-20  0.961541
2029-01-21  0.766609
2029-01-22  0.750703

[1828 rows x 1 columns]


In [22]:
# 57. Write a Pandas program to count number of columns of a DataFrame.
import pandas as pd
import numpy as np
d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(d)
print("Number of Columns of a Dataframe")
print(len(df.columns))

Number of Columns of a Dataframe
3


In [41]:
#Write a Pandas program to get topmost n records within each group of a DataFrame.

import pandas as pd
import numpy as np
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(d)
print("Original Dataframe")
print(df)
print("Top Most for Col1")
df1 = df.nlargest(3,'col1')
print(df1['col1'].values)
print("Top most for Col2")
df2 = df.nlargest(2,'col2')
print(df2['col2'].values)
print("Top most for column 3")
df3 = df.nlargest(6,'col3')
print(df3['col3'].values)

Original Dataframe
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
Top Most for Col1
[11  7  4]
Top most for Col2
[9 6]
Top most for column 3
[12 11  8  7  5  1]


In [54]:
#62. Write a Pandas program to remove first n rows of a given DataFrame.

import pandas as pd
import numpy as np
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(d)
df_after_removal = df.iloc[4:]

print(df_after_removal)

   col1  col2  col3
4     7     5     1
5    11     0    11


In [60]:
# 81. Write a Pandas program to get lowest n records within each group of a given DataFrame.

import pandas as pd
import numpy as np
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(d)
df1 = df.nsmallest(3,'col1')
df2 = df.nsmallest(3,'col2')
df3 = df.nsmallest(3,'col3')
print(df1['col1'].values)

[[1 4 7]
 [2 5 5]
 [3 6 8]]


In [64]:
import pandas as pd
df1 = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,85,None,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
df2 = pd.DataFrame({'W':[78,75,86,80,None],'X':[78,85,96,80,76], 'Y':[84,84,89,83,86],'Z':[86,97,96,72,83]});
print("Original DataFrames:")
print(df1)
print(df2)
print("\nCheck for inequality of the said dataframes:")
print(df1.ne(df2))


Original DataFrames:
      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  85.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  83  72
4   NaN  86.0  86  83
      W   X   Y   Z
0  78.0  78  84  86
1  75.0  85  84  97
2  86.0  96  89  96
3  80.0  80  83  72
4   NaN  76  86  83

Check for inequality of the said dataframes:
       W      X      Y      Z
0   True  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False  False
4   True   True  False  False


In [75]:
import pandas as pd
import numpy as np

sdata = {"c1":[120, 130 ,140, 150, np.nan, 170], "c2":[7, np.nan, 10, np.nan, 5.5, 16.5]}
df = pd.DataFrame(sdata)
df.index = pd._testing.makeDateIndex()[0:6]
print("Original DataFrame:")
print(df)
print("\nDataFrame after interpolate:")
print(df.interpolate)


Original DataFrame:
               c1    c2
2000-01-03  120.0   7.0
2000-01-04  130.0   NaN
2000-01-05  140.0  10.0
2000-01-06  150.0   NaN
2000-01-07    NaN   5.5
2000-01-10  170.0  16.5

DataFrame after interpolate:
<bound method DataFrame.interpolate of                c1    c2
2000-01-03  120.0   7.0
2000-01-04  130.0   NaN
2000-01-05  140.0  10.0
2000-01-06  150.0   NaN
2000-01-07    NaN   5.5
2000-01-10  170.0  16.5>


In [78]:
sr1 = pd.Series(['php', 'python', 'java', 'c#', 'c++'])
sr2 = pd.Series([1, 2, 3, 4, 5])

df_combined = pd.DataFrame(sr1,sr2).reset_index()
print(df_combined)
df_combined = pd.concat([sr1,sr2],axis=1)
print(df_combined)
df_combined = pd.DataFrame({"col1":sr1,"clo2":sr2})
print(df_combined)

   index       0
0      1  python
1      2    java
2      3      c#
3      4     c++
4      5     NaN
        0  1
0     php  1
1  python  2
2    java  3
3      c#  4
4     c++  5
     col1  clo2
0     php     1
1  python     2
2    java     3
3      c#     4
4     c++     5


In [83]:
# 70. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.
import pandas as pd
df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
      'age': [18, 22, 85, 50, 80, 5]
})
print("Original DataFrame")
print(df)
print("Age Group")
df['age_groups'] = pd.cut(df['age'],bins=[0,18,65,99],labels=['kid','adult','elder'])
print("After Grouping to Age Group")
print(df['age_groups'])
print("AFTER DATAFRAME")
print(df)

Original DataFrame
             name  age
0  Alberto Franco   18
1    Gino Mcneill   22
2     Ryan Parkes   85
3    Eesha Hinton   50
4    Syed Wharton   80
5   Kierra Gentry    5
Age Group
After Grouping to Age Group
0      kid
1    adult
2    elder
3    adult
4    elder
5      kid
Name: age_groups, dtype: category
Categories (3, object): ['kid' < 'adult' < 'elder']
AFTER DATAFRAME
             name  age age_groups
0  Alberto Franco   18        kid
1    Gino Mcneill   22      adult
2     Ryan Parkes   85      elder
3    Eesha Hinton   50      adult
4    Syed Wharton   80      elder
5   Kierra Gentry    5        kid


In [87]:
# 69. Write a Pandas program to merge datasets and check uniqueness.
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'Date_Of_Birth ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Age': [18.5, 21.2, 22.5, 22, 23]
})
print("Original DataFrame")
print(df)

df1 = df.copy(deep=True)
df = df.drop([0,1])
df1 = df1.drop([2])
print("DF DataFrame",df)
print("DF1 DataFrame",df1)
print("one_to_one")
df_one_to_one = pd.merge(df,df1,validate="one_to_one")
print(df_one_to_one)
df_one_to_many = pd.merge(df,df1,validate="one_to_many")
print("One to Many",df_one_to_many)
df_many_to_one = pd.merge(df,df1,validate="many_to_one")
print("Many to One \n",df_many_to_one)

Original DataFrame
             Name Date_Of_Birth    Age
0  Alberto Franco     17/05/2002  18.5
1    Gino Mcneill     16/02/1999  21.2
2     Ryan Parkes     25/09/1998  22.5
3    Eesha Hinton     11/05/2002  22.0
4    Syed Wharton     15/09/1997  23.0
DF DataFrame            Name Date_Of_Birth    Age
2   Ryan Parkes     25/09/1998  22.5
3  Eesha Hinton     11/05/2002  22.0
4  Syed Wharton     15/09/1997  23.0
DF1 DataFrame              Name Date_Of_Birth    Age
0  Alberto Franco     17/05/2002  18.5
1    Gino Mcneill     16/02/1999  21.2
3    Eesha Hinton     11/05/2002  22.0
4    Syed Wharton     15/09/1997  23.0
one_to_one
           Name Date_Of_Birth    Age
0  Eesha Hinton     11/05/2002  22.0
1  Syed Wharton     15/09/1997  23.0
One to Many            Name Date_Of_Birth    Age
0  Eesha Hinton     11/05/2002  22.0
1  Syed Wharton     15/09/1997  23.0
Many to One 
            Name Date_Of_Birth    Age
0  Eesha Hinton     11/05/2002  22.0
1  Syed Wharton     15/09/1997  23.0


# 68. Write a Pandas program to rename all columns with the same pattern of a given DataFrame.
